// ===== NOTES LIST ACTION =====
export const REQUEST_NOTES_ATTEMPT = 'REQUEST_NOTES_ATTEMPT';
export const REQUEST_NOTES_SUCCESS = 'REQUEST_NOTES_SUCCESS';
export const REQUEST_NOTES_FAILURE = 'REQUEST_NOTES_FAILURE';

// ===== ADD NOTES ACTION =====
export const ADD_NOTES_ATTEMPT = 'ADD_NOTES_ATTEMPT';
export const ADD_NOTES_SUCCESS = 'ADD_NOTES_SUCCESS';
export const ADD_NOTES_FAILURE = 'ADD_NOTES_FAILURE';

// ===== EDIT NOTES ACTION =====
export const EDIT_NOTES_ATTEMPT = 'EDIT_NOTES_ATTEMPT';
export const EDIT_NOTES_SUCCESS = 'EDIT_NOTES_SUCCESS';
export const EDIT_NOTES_FAILURE = 'EDIT_NOTES_FAILURE';

// ===== DELETE NOTES ACTION =====
export const DELETE_NOTES_ATTEMPT = 'DELETE_NOTES_ATTEMPT';
export const DELETE_NOTES_SUCCESS = 'DELETE_NOTES_SUCCESS';
export const DELETE_NOTES_FAILURE = 'DELETE_NOTES_FAILURE';
